# Use root/example as user/password credentials
version: '3.1'

services:

  mysqldb:
      container_name: server-teste
      image: mysql:5.7
      restart: always
      ports:
        - '3306:3306'
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=1234 
        - MYSQL_DATABASE=server-db
        - MYSQL_USER=tato
        - MYSQL_PASSWORD=1234